#if os(macOS)
import AppKit
import Carbon.HIToolbox
import MurmurCore

/// Puts text at the cursor of whatever app has focus.
@MainActor
final class TextInserter {
    // Clipboard managers that follow nspasteboard.org conventions skip items marked like this.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    enum Outcome {
        case inserted
        /// Nothing that takes text had focus, so the text was left on the clipboard instead.
        case copiedOnly
    }

    @discardableResult
    func insert(_ text: String, config: InsertionConfig) async -> Outcome {
        let pasteboard = NSPasteboard.general
        if Self.focusedTarget() == .notText {
            // Pasting now would lose the words (or trigger a shortcut in, say, Finder).
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            return .copiedOnly
        }
        let saved = config.restoreClipboard ? snapshot(pasteboard) : nil

        switch config.method {
        case .paste:
            pasteboard.clearContents()
            if config.restoreClipboard {
                // It is only there for a moment; keep it out of clipboard history.
                pasteboard.declareTypes([.string, Self.transientType, Self.autoGeneratedType], owner: nil)
                pasteboard.setData(Data(), forType: Self.transientType)
                pasteboard.setData(Data(), forType: Self.autoGeneratedType)
            }
            pasteboard.setString(text, forType: .string)
            let ourChange = pasteboard.changeCount
            postCommandV()
            if let saved {
                // Give the target app time to read the pasteboard before putting the old contents back.
                // This wait must run in full even if the job is cancelled (Esc): the Cmd-V is already
                // on its way, and restoring early would paste the old clipboard instead.
                await Self.pause(milliseconds: max(100, config.restoreDelayMs))
                if pasteboard.changeCount == ourChange { restore(saved, to: pasteboard) }
            }

        case .type:
            await typeText(text)
            if !config.restoreClipboard {
                // Same promise as paste mode: the transcript is on the clipboard afterwards.
                pasteboard.clearContents()
                pasteboard.setString(text, forType: .string)
            }
        }
        return .inserted
    }

    // MARK: Focus

    /// What has keyboard focus, as far as Accessibility can tell.
    private enum Focus {
        case element(AXUIElement)
        /// Accessibility answered: nothing has focus (the desktop, an empty screen).
        case nothing
        /// No permission, a busy app, or one that doesn't support Accessibility.
        case unknown
    }

    /// Only a definite "nothing" or a non-text role skips the paste; anything uncertain pastes as before.
    private static func focusedTarget() -> TextTarget.Verdict {
        guard AXIsProcessTrusted() else { return .text }
        switch focus() {
        case .unknown:
            return .text
        case .nothing:
            return TextTarget.verdict(role: nil, editable: nil)
        case let .element(element):
            var role: CFTypeRef?
            guard AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &role) == .success,
                  let name = role as? String else { return .text }
            return TextTarget.verdict(role: name, editable: isEditable(element))
        }
    }

    /// Whether the element takes text: its value can be set, or it has a text selection.
    private static func isEditable(_ element: AXUIElement) -> Bool? {
        var settable = DarwinBoolean(false)
        if AXUIElementIsAttributeSettable(element, kAXValueAttribute as CFString, &settable) == .success, settable.boolValue {
            return true
        }
        var range: CFTypeRef?
        if AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &range) == .success {
            return true
        }
        return nil
    }

    private static func focus() -> Focus {
        let system = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(system, 0.2)
        var focused: CFTypeRef?
        switch AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused) {
        case .success:
            guard let focused, CFGetTypeID(focused) == AXUIElementGetTypeID() else { return .unknown }
            return .element(focused as! AXUIElement)
        case .noValue:
            return .nothing
        default:
            return .unknown
        }
    }

    // MARK: Pasteboard

    private func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private func restore(_ items: [NSPasteboardItem], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        if !items.isEmpty { pasteboard.writeObjects(items) }
    }

    // MARK: Keystrokes

    private func postCommandV() {
        let source = CGEventSource(stateID: .hidSystemState)
        let v = Self.keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        for keyDown in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: keyDown) else { continue }
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: HotkeyMonitor.syntheticEventMarker)
            event.post(tap: .cghidEventTap)
        }
    }

    private func typeText(_ text: String) async {
        let source = CGEventSource(stateID: .hidSystemState)
        for piece in Keystrokes.pieces(for: text) {
            switch piece {
            case .newline:
                postKey(CGKeyCode(kVK_Return), source: source)
            case let .text(units):
                for keyDown in [true, false] {
                    guard let event = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: keyDown) else { continue }
                    event.flags = []
                    units.withUnsafeBufferPointer { buffer in
                        event.keyboardSetUnicodeString(stringLength: buffer.count, unicodeString: buffer.baseAddress)
                    }
                    event.setIntegerValueField(.eventSourceUserData, value: HotkeyMonitor.syntheticEventMarker)
                    event.post(tap: .cghidEventTap)
                }
            }
            // Some apps drop events that arrive too fast. Once typing has started it finishes,
            // even on Esc, so the text is never left half-typed.
            await Self.pause(milliseconds: 4)
        }
    }

    /// Sleeps without being cut short by task cancellation.
    private static func pause(milliseconds: Int) async {
        await Task.detached {
            try? await Task.sleep(nanoseconds: UInt64(milliseconds) * 1_000_000)
        }.value
    }

    private func postKey(_ code: CGKeyCode, source: CGEventSource?) {
        for keyDown in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source, virtualKey: code, keyDown: keyDown) else { continue }
            event.flags = []
            event.setIntegerValueField(.eventSourceUserData, value: HotkeyMonitor.syntheticEventMarker)
            event.post(tap: .cghidEventTap)
        }
    }

    /// The key that types `character` in the current keyboard layout, so Cmd-V still means
    /// paste on Dvorak, AZERTY and friends. Nil for layouts without that character.
    private static func keyCode(for character: String) -> CGKeyCode? {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let property = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return nil
        }
        let layoutData = Unmanaged<CFData>.fromOpaque(property).takeUnretainedValue() as Data
        return layoutData.withUnsafeBytes { raw -> CGKeyCode? in
            guard let layout = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return nil }
            for code in 0..<128 {
                var deadKeyState: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(layout, UInt16(code), UInt16(kUCKeyActionDisplay), 0,
                                            UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysMask),
                                            &deadKeyState, chars.count, &length, &chars)
                if status == noErr, length > 0, String(utf16CodeUnits: chars, count: length) == character {
                    return CGKeyCode(code)
                }
            }
            return nil
        }
    }
}
#endif
